name = "HTMXObjects"
uuid = "b12ef442-5798-4353-80f3-9562b03a0cb6"
authors = ["Nikolas Siccha <nikolassiccha@gmail.com>"]
version = "0.1.0"

[deps]
DynamicObjects = "23d02862-63fe-4c6e-8fdb-1d52cbbd39d5"
HTMX = "27f3e1ef-6ef8-44dc-9e9a-2fb23ed44e83"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
Oxygen = "df9a0d86-3283-4920-82dc-4555fc0d1d8b"

[compat]
julia = "1"

[sources.DynamicObjects]
url = "https://github.com/nsiccha/DynamicObjects.jl.git"

[sources.HTMX]
url = "https://github.com/nsiccha/HTMX.jl.git"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
